services:
  - type: web
    name: mavilla-django
    runtime: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: maisondatabase
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://mavilla.onrender.com,https://ton-frontend-react.com
      - key: CLOUDINARY_CLOUD_NAME
        value: dwg9lwgyt
      - key: CLOUDINARY_API_KEY
        value: 222745575696657
      - key: CLOUDINARY_API_SECRET
        value: ZCwHe5JOFdOMrT12A1m7d911WY4
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: POETRY_VERSION
        value: none

databases:
  - name: maisondatabase
    region: oregon
    plan: free
    databaseName: maisondatabase
    user: maisondatabase_user