# Generated by Django 4.2 on 2026-02-23 11:06

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_proprietaire', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('adresse_complete', models.TextField(blank=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type_hotel', models.CharField(choices=[('hotel', 'Hôtel'), ('motel', 'Motel'), ('auberge', 'Auberge'), ('resort', 'Résort'), ('boutique', 'Hôtel boutique')], default='hotel', max_length=20)),
                ('categorie', models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=3)),
                ('prix_nuit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('services', models.TextField(blank=True)),
                ('nombre_chambres', models.PositiveIntegerField(default=0)),
                ('chambres_disponibles', models.PositiveIntegerField(default=0)),
                ('heure_check_in', models.TimeField(default='14:00')),
                ('heure_check_out', models.TimeField(default='12:00')),
                ('ville', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_hotels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('adresse_complete', models.TextField(blank=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_maison', models.CharField(choices=[('vente', 'À vendre'), ('location', 'À louer'), ('vacances', 'Location vacances')], max_length=10)),
                ('categorie', models.CharField(choices=[('maison', 'Maison'), ('appartement', 'Appartement'), ('villa', 'Villa'), ('studio', 'Studio'), ('duplex', 'Duplex')], default='maison', max_length=20)),
                ('titre', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=100)),
                ('prix_promotion', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('nombre_chambres', models.PositiveIntegerField()),
                ('nombre_salles_de_bain', models.PositiveIntegerField()),
                ('nombre_salon', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_cuisines', models.PositiveIntegerField(blank=True, null=True)),
                ('surface', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('piscine', models.BooleanField(default=False)),
                ('jardin', models.BooleanField(default=False)),
                ('garage', models.BooleanField(default=False)),
                ('climatiseur', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('meuble', models.BooleanField(default=False)),
                ('quartier', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('vue_count', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_maisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('adresse_complete', models.TextField(blank=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_parcelle', models.CharField(choices=[('agricole', 'Agricole'), ('residentielle', 'Résidentielle'), ('commerciale', 'Commerciale'), ('industrielle', 'Industrielle'), ('loisir', 'Loisir')], default='residentielle', max_length=20)),
                ('titre', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=20)),
                ('surface', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quartier', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_parcelles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('drapeau', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('indicatif', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Publicite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('photos', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('lien', models.URLField(blank=True, null=True)),
                ('type_pub', models.CharField(choices=[('maison', 'Maison'), ('parcelle', 'Parcelle'), ('hotel', 'Hôtel'), ('residence', 'Résidence'), ('general', 'Général')], default='general', max_length=20)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('clic_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', '-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('adresse_complete', models.TextField(blank=True)),
                ('ville', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_residence', models.CharField(choices=[('residentiel', 'Résidentiel'), ('etudiant', 'Résidence étudiante'), ('senior', 'Résidence senior'), ('touristique', 'Résidence touristique')], max_length=20)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('services_inclus', models.TextField(blank=True)),
                ('reglement_interieur', models.TextField(blank=True)),
                ('nombre_appartements', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_residences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video')),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='maison.maison')),
            ],
        ),
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(max_length=50)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'type')},
            },
        ),
        migrations.CreateModel(
            name='ResidencePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='maison.residence')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('is_principale', models.BooleanField(default=False)),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='maison.maison')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ParcellePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='maison.parcelle')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('message', 'Message'), ('visite', 'Visite'), ('like', 'Like'), ('comment', 'Commentaire'), ('reservation', 'Réservation'), ('system', 'Système')], default='system', max_length=50)),
                ('data', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('is_principale', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='maison.hotel')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DemandeVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bien_type', models.CharField(max_length=50)),
                ('bien_id', models.UUIDField()),
                ('date_souhaitee', models.DateTimeField()),
                ('message', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('effectue', 'Effectué')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('sujet', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type_contact', models.CharField(choices=[('visite', 'Demande de visite'), ('info', "Demande d'information"), ('location', 'Demande de location'), ('achat', "Demande d'achat"), ('autre', 'Autre')], default='info', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('is_traite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('note', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='maison.maison')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='maison.maison')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('maison', 'user')},
            },
        ),
        migrations.CreateModel(
            name='HotelNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='maison.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('hotel', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='maison.maison')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'unique_together': {('maison', 'user')},
            },
        ),
    ]
