# Generated by Django 4.2 on 2026-07-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
    ]
