# Generated by Django 4.2 on 2026-02-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='1', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
