# Generated by Django 5.2.8 on 2026-01-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maison", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=255),
        ),
    ]
