# Generated by Django 5.2.8 on 2026-01-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maison", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicite",
            name="lien",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="publicite",
            name="photos",
            field=models.ImageField(blank=True, null=True, upload_to="publicites/"),
        ),
        migrations.AlterField(
            model_name="publicite",
            name="titre",
            field=models.CharField(max_length=255),
        ),
    ]
