# Generated by Django 4.2 on 2026-07-07 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('maison', '0002_appversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_bien', models.CharField(max_length=20)),
                ('type_transaction', models.CharField(default='location', max_length=20)),
                ('prix_max', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('quartier', models.CharField(blank=True, max_length=255)),
                ('nombre_chambres', models.IntegerField(blank=True, null=True)),
                ('nombre_salles_bain', models.IntegerField(blank=True, null=True)),
                ('surface', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dimension', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='hotelnote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='hotelnote',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='hotelnote',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='favori',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='maison',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favori',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='favori',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='like',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='residence',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_residences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favori',
            unique_together={('user', 'content_type', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='commentaire',
            index=models.Index(fields=['content_type', 'object_id'], name='maison_comm_content_8eb48c_idx'),
        ),
        migrations.DeleteModel(
            name='HotelNote',
        ),
        migrations.AddField(
            model_name='alerte',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='favori',
            name='maison',
        ),
        migrations.RemoveField(
            model_name='like',
            name='maison',
        ),
    ]
