# Generated by Django 5.2.8 on 2026-02-05 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maison", "0002_message_notification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={},
        ),
        migrations.RenameField(
            model_name="message",
            old_name="content",
            new_name="text",
        ),
        migrations.RemoveField(
            model_name="message",
            name="is_read",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="content",
        ),
        migrations.AddField(
            model_name="notification",
            name="body",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(default="system", max_length=50),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
