# Generated by Django 4.2 on 2026-07-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison', '0003_alerte_alter_hotelnote_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
