# Generated by Django 4.2 on 2026-07-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison', '0004_user_adresse_user_bio_user_pays_user_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
