# Generated by Django 6.0.5 on 2026-07-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maison', '0006_supportticket_professionalrequest_mediation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_proprietaire',
        ),
    ]
